// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace OSSFinder.Areas.HelpPage.Controllers {
    public partial class HelpController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HelpController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Api() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Api);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HelpController Actions { get { return MVC.HelpPage.Help; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "HelpPage";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Help";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string Api = "Api";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Api = "~/Areas/HelpPage/Views/Help/Api.cshtml";
            public readonly string Index = "~/Areas/HelpPage/Views/Help/Index.cshtml";
            static readonly _DisplayTemplates s_DisplayTemplates = new _DisplayTemplates();
            public _DisplayTemplates DisplayTemplates { get { return s_DisplayTemplates; } }
            public partial class _DisplayTemplates{
                public readonly string ApiGroup = "ApiGroup";
                public readonly string HelpPageApiModel = "HelpPageApiModel";
                public readonly string ImageSample = "ImageSample";
                public readonly string InvalidSample = "InvalidSample";
                public readonly string Parameters = "Parameters";
                public readonly string Samples = "Samples";
                public readonly string TextSample = "TextSample";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_HelpController: OSSFinder.Areas.HelpPage.Controllers.HelpController {
        public T4MVC_HelpController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Api(string apiId) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Api);
            callInfo.RouteValueDictionary.Add("apiId", apiId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
