//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSSFinder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSSFinder.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already logged in!.
        /// </summary>
        internal static string AlreadyLoggedIn {
            get {
                return ResourceManager.GetString("AlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; authentication provider is disabled and cannot be used to authenticate.
        /// </summary>
        internal static string AuthenticationProviderDisabled {
            get {
                return ResourceManager.GetString("AuthenticationProviderDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! You can&apos;t remove the only credential that can be used to log in to the website!.
        /// </summary>
        internal static string CannotRemoveOnlyLoginCredential {
            get {
                return ResourceManager.GetString("CannotRemoveOnlyLoginCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external account has been removed.
        /// </summary>
        internal static string CredentialRemoved {
            get {
                return ResourceManager.GetString("CredentialRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        internal static string CredentialType_ApiKey {
            get {
                return ResourceManager.GetString("CredentialType_ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string CredentialType_Password {
            get {
                return ResourceManager.GetString("CredentialType_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password you provided is incorrect..
        /// </summary>
        internal static string CurrentPasswordIncorrect {
            get {
                return ResourceManager.GetString("CurrentPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NuGet service is experiencing a service interruption. Try requesting a specific package version instead..
        /// </summary>
        internal static string DatabaseUnavailable_TrySpecificVersion {
            get {
                return ResourceManager.GetString("DatabaseUnavailable_TrySpecificVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address &apos;{0}&apos; is being used..
        /// </summary>
        internal static string EmailAddressBeingUsed {
            get {
                return ResourceManager.GetString("EmailAddressBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email preferences have been updated.
        /// </summary>
        internal static string EmailPreferencesUpdated {
            get {
                return ResourceManager.GetString("EmailPreferencesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} was added to your account and can now be used to log in. If you did not request this change, please reply to this email to contact support..
        /// </summary>
        internal static string Emails_CredentialAdded_Body {
            get {
                return ResourceManager.GetString("Emails_CredentialAdded_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1} added to your account.
        /// </summary>
        internal static string Emails_CredentialAdded_Subject {
            get {
                return ResourceManager.GetString("Emails_CredentialAdded_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} was removed from your account and can no longer be used to log in. If you did not request this change, please reply to this email to contact support..
        /// </summary>
        internal static string Emails_CredentialRemoved_Body {
            get {
                return ResourceManager.GetString("Emails_CredentialRemoved_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1} removed from your account.
        /// </summary>
        internal static string Emails_CredentialRemoved_Subject {
            get {
                return ResourceManager.GetString("Emails_CredentialRemoved_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word on the street is you lost your password. Sorry to hear it!
        ///If you haven&apos;t forgotten your password you can safely ignore this email. Your password has not been changed.
        ///
        ///Click the following link within the next {0} hours to reset your password:
        ///
        ///[{1}]({1})
        ///
        ///Thanks,
        ///The {2} Team.
        /// </summary>
        internal static string Emails_ForgotPassword_Body {
            get {
                return ResourceManager.GetString("Emails_ForgotPassword_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Please reset your password..
        /// </summary>
        internal static string Emails_ForgotPassword_Subject {
            get {
                return ResourceManager.GetString("Emails_ForgotPassword_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word on the street is you want to set a password for your account.
        ///If you didn&apos;t request a password, you can safely ignore this message. A password has not yet been set.
        ///
        ///Click the following link within the next {0} hours to set your password:
        ///
        ///[{1}]({1})
        ///
        ///Thanks,
        ///The {2} Team.
        /// </summary>
        internal static string Emails_SetPassword_Body {
            get {
                return ResourceManager.GetString("Emails_SetPassword_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] Please set your password..
        /// </summary>
        internal static string Emails_SetPassword_Subject {
            get {
                return ResourceManager.GetString("Emails_SetPassword_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new email address was saved!.
        /// </summary>
        internal static string EmailUpdated {
            get {
                return ResourceManager.GetString("EmailUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address has been changed! We sent a confirmation email to verify your new email. When you confirm the new email address, it will take effect and we will forget the old one..
        /// </summary>
        internal static string EmailUpdated_ConfirmationRequired {
            get {
                return ResourceManager.GetString("EmailUpdated_ConfirmationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your external account credential expired or you did not allow us access to your account. Try logging in again..
        /// </summary>
        internal static string ExternalAccountLinkExpired {
            get {
                return ResourceManager.GetString("ExternalAccountLinkExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot send added/removed email for credentials of type &apos;{0}&apos;.
        /// </summary>
        internal static string MessageService_CannotSendEmailForCredential {
            get {
                return ResourceManager.GetString("MessageService_CannotSendEmailForCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft account.
        /// </summary>
        internal static string MicrosoftAccount_AccountNoun {
            get {
                return ResourceManager.GetString("MicrosoftAccount_AccountNoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft account.
        /// </summary>
        internal static string MicrosoftAccount_Caption {
            get {
                return ResourceManager.GetString("MicrosoftAccount_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with a Microsoft account.
        /// </summary>
        internal static string MicrosoftAccount_SignInMessage {
            get {
                return ResourceManager.GetString("MicrosoftAccount_SignInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Credentials match &apos;{0}&apos; credential with Key {1}.
        /// </summary>
        internal static string MultipleMatchingCredentials {
            get {
                return ResourceManager.GetString("MultipleMatchingCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot be null or an empty string.
        /// </summary>
        internal static string ParameterCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ParameterCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed.
        /// </summary>
        internal static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password credentials cannot be used with Authenticate(Credential). Use Authenticate(string, string) instead..
        /// </summary>
        internal static string PasswordCredentialsCannotBeUsedHere {
            get {
                return ResourceManager.GetString("PasswordCredentialsCannotBeUsedHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been removed.
        /// </summary>
        internal static string PasswordRemoved {
            get {
                return ResourceManager.GetString("PasswordRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set.
        /// </summary>
        internal static string PasswordSet {
            get {
                return ResourceManager.GetString("PasswordSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource can only be accessed via SSL..
        /// </summary>
        internal static string SSLRequired {
            get {
                return ResourceManager.GetString("SSLRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized.
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown authentication provider: &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownAuthenticationProvider {
            get {
                return ResourceManager.GetString("UnknownAuthenticationProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot reset your password until you confirm your account..
        /// </summary>
        internal static string UserIsNotYetConfirmed {
            get {
                return ResourceManager.GetString("UserIsNotYetConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique user with that username or email address and password does not exist. Try logging on with your username if you were using an email address to log on..
        /// </summary>
        internal static string UsernameAndPasswordNotFound {
            get {
                return ResourceManager.GetString("UsernameAndPasswordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username &apos;{0}&apos; is not available..
        /// </summary>
        internal static string UsernameNotAvailable {
            get {
                return ResourceManager.GetString("UsernameNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with the provided user name does not exist..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
