// <auto-generated />
namespace OSSFinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SiteSettings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SiteSettings));
        
        string IMigrationMetadata.Id
        {
            get { return "201312290346121_SiteSettings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
