// <auto-generated />
namespace OSSFinder.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Dependencies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dependencies));
        
        string IMigrationMetadata.Id
        {
            get { return "201401080611234_Dependencies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
